### ISSUE TITLE
Existing pads still accessible?

### ISSUE THREAD

**Issue by rasos** [neurolit/etherpad-lite-frontend#1]
Before we install this very useful etherpad extension: what happens with existing pads? Are they still accessible without password, even if not in the create_pad DB?
Could not find any hint in the documentation about this.

**Comment by neurolit** [comment]
Hi! Sorry for keeping you waiting.

This repository is no etherpad extension. It's an application **in front of** Etherpad-Lite. Existing pads still exist: they are accessible without any password, as before. The documentation is maybe no as complete as I'd like ;-)

Generally speaking, you'll have 2 addresses: one for this frontend, and the other for Etherpad-Lite. In Etherpad-Lite, you will disable the creation of pad, but with the API. And then you can use this frontend in order to create new pads, protected or not.
